### ISSUE TITLE
Bot on Heroku not working

### ISSUE THREAD

**Issue by FantasyGmng** [kenng69/modmailbotkenng#6]
Logs:

`2019-03-28T12:54:11.052072+00:00 heroku[worker.1]: Starting process with command `python bot.py`
2019-03-28T12:54:11.052072+00:00 heroku[worker.1]: Starting process with command `python bot.py`
2019-03-28T12:54:11.604923+00:00 heroku[worker.1]: State changed from starting to up
2019-03-28T12:54:14.136438+00:00 app[worker.1]: ---------------
2019-03-28T12:54:14.136454+00:00 app[worker.1]: Modmail connected!
2019-03-28T12:54:14.136459+00:00 app[worker.1]: No status set.
2019-03-28T12:54:16.139754+00:00 app[worker.1]: 
2019-03-28T12:54:16.139783+00:00 app[worker.1]: ---------------
2019-03-28T12:54:16.139785+00:00 app[worker.1]: Client is ready!
2019-03-28T12:54:16.139786+00:00 app[worker.1]: ---------------
2019-03-28T12:54:16.139787+00:00 app[worker.1]: Author: kenng#4401
2019-03-28T12:54:16.139788+00:00 app[worker.1]: ---------------
2019-03-28T12:54:16.139791+00:00 app[worker.1]: Logged in as: TyrNE™ COD ModMail#6262
2019-03-28T12:54:16.139791+00:00 app[worker.1]: User ID: 560775364247289856
2019-03-28T12:54:16.139792+00:00 app[worker.1]: ---------------
2019-03-28T12:54:16.139793+00:00 app[worker.1]: 
2019-03-28T12:54:47.017794+00:00 app[worker.1]: Ignoring exception in command ping:
2019-03-28T12:54:47.018573+00:00 app[worker.1]: Traceback (most recent call last):
2019-03-28T12:54:47.018612+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 860, in invoke
2019-03-28T12:54:47.018614+00:00 app[worker.1]:     await ctx.command.invoke(ctx)
2019-03-28T12:54:47.018616+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/core.py", line 691, in invoke
2019-03-28T12:54:47.018618+00:00 app[worker.1]:     await self.prepare(ctx)
2019-03-28T12:54:47.018620+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/core.py", line 655, in prepare
2019-03-28T12:54:47.018621+00:00 app[worker.1]:     await self._parse_arguments(ctx)
2019-03-28T12:54:47.018624+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/core.py", line 570, in _parse_arguments
2019-03-28T12:54:47.018625+00:00 app[worker.1]:     transformed = await self.transform(ctx, param)
2019-03-28T12:54:47.018642+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/core.py", line 426, in transform
2019-03-28T12:54:47.018643+00:00 app[worker.1]:     raise MissingRequiredArgument(param)
2019-03-28T12:54:47.018669+00:00 app[worker.1]: discord.ext.commands.errors.MissingRequiredArgument: ctx is a required argument that is missing.`

**Comment by sasial-roblox** [comment]
Can you try again? Sometimes if you delete the Heroku app and try again it works.
